/*
 * This file is generated by jOOQ.
 */
package com.otto.lab3.jooq.tables;


import com.otto.lab3.jooq.Keys;
import com.otto.lab3.jooq.S335109;
import com.otto.lab3.jooq.tables.records.HitChecksRecord;

import java.time.OffsetDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HitChecks extends TableImpl<HitChecksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s335109.hit_checks</code>
     */
    public static final HitChecks HIT_CHECKS = new HitChecks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HitChecksRecord> getRecordType() {
        return HitChecksRecord.class;
    }

    /**
     * The column <code>s335109.hit_checks.id</code>.
     */
    public final TableField<HitChecksRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>s335109.hit_checks.session_id</code>.
     */
    public final TableField<HitChecksRecord, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.x</code>.
     */
    public final TableField<HitChecksRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.y</code>.
     */
    public final TableField<HitChecksRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.r</code>.
     */
    public final TableField<HitChecksRecord, Double> R = createField(DSL.name("r"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.calling_date</code>.
     */
    public final TableField<HitChecksRecord, OffsetDateTime> CALLING_DATE = createField(DSL.name("calling_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.execution_time</code>.
     */
    public final TableField<HitChecksRecord, Long> EXECUTION_TIME = createField(DSL.name("execution_time"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.hit_status</code>.
     */
    public final TableField<HitChecksRecord, Boolean> HIT_STATUS = createField(DSL.name("hit_status"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>s335109.hit_checks.timezone</code>.
     */
    public final TableField<HitChecksRecord, String> TIMEZONE = createField(DSL.name("timezone"), SQLDataType.VARCHAR.nullable(false), this, "");

    private HitChecks(Name alias, Table<HitChecksRecord> aliased) {
        this(alias, aliased, null);
    }

    private HitChecks(Name alias, Table<HitChecksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>s335109.hit_checks</code> table reference
     */
    public HitChecks(String alias) {
        this(DSL.name(alias), HIT_CHECKS);
    }

    /**
     * Create an aliased <code>s335109.hit_checks</code> table reference
     */
    public HitChecks(Name alias) {
        this(alias, HIT_CHECKS);
    }

    /**
     * Create a <code>s335109.hit_checks</code> table reference
     */
    public HitChecks() {
        this(DSL.name("hit_checks"), null);
    }

    public <O extends Record> HitChecks(Table<O> child, ForeignKey<O, HitChecksRecord> key) {
        super(child, key, HIT_CHECKS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : S335109.S335109;
    }

    @Override
    public Identity<HitChecksRecord, Integer> getIdentity() {
        return (Identity<HitChecksRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HitChecksRecord> getPrimaryKey() {
        return Keys.HIT_CHECKS_PKEY;
    }

    @Override
    public HitChecks as(String alias) {
        return new HitChecks(DSL.name(alias), this);
    }

    @Override
    public HitChecks as(Name alias) {
        return new HitChecks(alias, this);
    }

    @Override
    public HitChecks as(Table<?> alias) {
        return new HitChecks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HitChecks rename(String name) {
        return new HitChecks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HitChecks rename(Name name) {
        return new HitChecks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HitChecks rename(Table<?> name) {
        return new HitChecks(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, Double, Double, Double, OffsetDateTime, Long, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Integer, ? super String, ? super Double, ? super Double, ? super Double, ? super OffsetDateTime, ? super Long, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Integer, ? super String, ? super Double, ? super Double, ? super Double, ? super OffsetDateTime, ? super Long, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
