/*
 * This file is generated by jOOQ.
 */
package com.otto.lab3.jooq;


import com.otto.lab3.jooq.tables.HitChecks;
import com.otto.lab3.jooq.tables.records.HitChecksRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * s335109.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HitChecksRecord> HIT_CHECKS_PKEY = Internal.createUniqueKey(HitChecks.HIT_CHECKS, DSL.name("hit_checks_pkey"), new TableField[] { HitChecks.HIT_CHECKS.ID }, true);
}
