/*
 * This file is generated by jOOQ.
 */
package com.otto.lab3.jooq;


import com.otto.lab3.jooq.tables.HitChecks;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S335109 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s335109</code>
     */
    public static final S335109 S335109 = new S335109();

    /**
     * The table <code>s335109.hit_checks</code>.
     */
    public final HitChecks HIT_CHECKS = HitChecks.HIT_CHECKS;

    /**
     * No further instances allowed
     */
    private S335109() {
        super("s335109", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            HitChecks.HIT_CHECKS
        );
    }
}
