/*
 * This file is generated by jOOQ.
 */
package com.otto.lab3.jooq;


import com.otto.lab3.jooq.tables.HitChecks;


/**
 * Convenience access to all tables in s335109.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s335109.hit_checks</code>.
     */
    public static final HitChecks HIT_CHECKS = HitChecks.HIT_CHECKS;
}
